name: wiretap_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  dart_jsonwebtoken: ^3.1.1
  dotenv: ^4.2.0
  equatable: ^2.0.7
  hashlib: ^1.21.2
  libserialport: ^0.3.0+1
  mailer: ^6.4.1
  objectbox: ^4.1.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.1.1
  objectbox_generator: ^4.1.0
  test: ^1.25.15
